name: todoagent
description: "A new Flutter project."
# 禁止将此包意外发布到 pub.dev
publish_to: 'none'

# 应用版本号和构建号定义
version: 1.0.0+1

environment:
  sdk: ^3.7.2

# 依赖项配置
dependencies:
  flutter:
    sdk: flutter

  # iOS风格图标支持
  cupertino_icons: ^1.0.8

# 开发依赖项配置
dev_dependencies:
  flutter_test:
    sdk: flutter

  # 代码规范检查工具
  flutter_lints: ^5.0.0

# Flutter特定配置
flutter:

  # 包含Material图标字体
  uses-material-design: true

  # 资源文件配置示例
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # 自定义字体配置示例
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
